import { Link } from 'react-router-dom';
import '../styles/HomePage.css';

const painPoints = [
  ['01', 'Sổ tay dễ thất lạc', 'Mưa ướt, trang rách, tìm lại một khoản chi của vụ trước cũng thành việc khó.'],
  ['02', 'Không rõ vườn nào đang lời', 'Cà phê, sầu riêng, mắc ca thường trồng xen. Gộp chung số liệu khiến quyết định bị mù.'],
  ['03', 'Kế toán riêng quá tốn kém', 'Chủ vườn cần một cách ghi chép đơn giản, đủ chắc để tự kiểm tra mỗi tuần.'],
  ['04', 'Hóa đơn cũ không tra được', 'Chi phí nằm trong túi giấy, đến cuối vụ không còn nhớ đã mua gì và cho lô nào.'],
];

const featureData = [
  { number: '01', title: 'Nhật ký canh tác', copy: 'Ghi việc đã làm theo từng lô cây, ngay ngoài vườn. Có ngày, người thực hiện và ghi chú để cả nhà cùng hiểu.', kind: 'journal' },
  { number: '02', title: 'Vật tư & chi phí', copy: 'Biết tiền đang đi vào đâu: phân, thuốc, nhân công hay một khoản phát sinh nhỏ nhưng lặp lại mỗi tuần.', kind: 'costs' },
  { number: '03', title: 'Báo cáo lợi nhuận', copy: 'Tách riêng cà phê và sầu riêng trong cùng một vườn, để biết cây nào đang nuôi cây nào.', kind: 'profit' },
  { number: '04', title: 'Số hóa hóa đơn', copy: 'Chụp hóa đơn bằng camera, lưu cùng khoản chi. Không còn túi giấy cần lục vào cuối vụ.', kind: 'receipt' },
];

function PhoneScreen({ kind }) {
  if (kind === 'journal') return <div className="phone-screen journal-screen"><div className="screen-top"><span>09:41</span><span>● ● ●</span></div><p className="screen-kicker">NHẬT KÝ HÔM NAY</p><h4>Bón phân lần 2</h4><p className="screen-muted">Lô Sầu riêng 02 · 05/09/2026</p><div className="screen-row"><span className="screen-icon">↗</span><div><b>Phân hữu cơ</b><small>120 kg · Đã hoàn tất</small></div></div><div className="screen-note">Mưa nhẹ sau khi bón, cây hấp thụ tốt.</div><div className="screen-button">Lưu nhật ký</div></div>;
  if (kind === 'costs') return <div className="phone-screen costs-screen"><div className="screen-top"><span>Kho vật tư</span><span className="screen-plus">+</span></div><div className="cost-total"><small>CHI PHÍ THÁNG 9</small><strong>18.420.000 đ</strong></div><div className="cost-line"><span>Phân bón <i>62%</i></span><b>11,4 tr</b></div><div className="meter"><span style={{ width: '62%' }} /></div><div className="cost-line"><span>Nhân công <i>24%</i></span><b>4,4 tr</b></div><div className="meter amber"><span style={{ width: '24%' }} /></div><div className="cost-line"><span>Khác <i>14%</i></span><b>2,6 tr</b></div><div className="meter brown"><span style={{ width: '14%' }} /></div></div>;
  if (kind === 'profit') return <div className="phone-screen profit-screen"><div className="screen-top"><span>Lợi nhuận vụ này</span><span>⌁</span></div><p className="screen-muted">Vườn Đồi Gió · 2 ha</p><div className="profit-total"><small>TẠM TÍNH</small><strong>+86,4 tr</strong><span>↑ 12,8% so với vụ trước</span></div><div className="profit-bars"><div><span style={{ height: '70%' }} /><small>Cà phê</small></div><div><span className="bar-dark" style={{ height: '92%' }} /><small>Sầu riêng</small></div><div><span style={{ height: '48%' }} /><small>Mắc ca</small></div></div></div>;
  return <div className="phone-screen receipt-screen"><div className="screen-top"><span>Hóa đơn mới</span><span>⋮</span></div><div className="receipt-photo"><span>HÓA ĐƠN VẬT TƯ</span><b>05 · 09 · 2026</b><strong>1.280.000 đ</strong></div><div className="receipt-field"><small>Đơn vị bán</small><b>Vật tư Nông Lâm</b></div><div className="receipt-field"><small>Đã gắn vào</small><b>Vườn Đồi Gió · Cà phê</b></div><div className="screen-button dark-button">Xác nhận khoản chi</div></div>;
}

function HomePage() {
  return <div className="farm-landing">
    <section className="landing-hero"><div className="hero-grain" /><div className="container landing-hero-inner"><div className="hero-copy"><p className="landing-eyebrow"><span /> HỆ THỐNG QUẢN LÝ CHO VƯỜN CÂY DÀI NGÀY</p><h1>Sổ vườn rõ ràng.<br /><em>Lời lỗ có căn cứ.</em></h1><p className="hero-lead">Farm-Farmer giúp chủ vườn ghi lại từng việc đã làm, từng khoản đã chi và nhìn thấy hiệu quả thật của cà phê, sầu riêng, mắc ca trong cùng một nơi.</p><div className="landing-actions"><Link className="landing-primary" to="/register">Dùng thử miễn phí <span>↗</span></Link><a className="landing-secondary" href="#demo">Xem cách hoạt động <span>↓</span></a></div><p className="hero-note">Không cần kế toán riêng · Bắt đầu với vườn đầu tiên của bạn</p></div><div className="hero-visual" aria-label="Bản xem trước báo cáo vườn Đồi Gió"><div className="field-label">VƯỜN ĐỒI GIÓ <span>● ĐANG THEO DÕI</span></div><div className="profit-board"><div className="board-head"><div><small>LỢI NHUẬN TẠM TÍNH · VỤ 2026</small><strong>+86.420.000 <i>đ</i></strong></div><span className="board-mark">FF</span></div><div className="board-chart"><div className="chart-y"><span>100tr</span><span>50tr</span><span>0</span></div><div className="chart-area"><div className="chart-line" /><div className="chart-point p1" /><div className="chart-point p2" /><div className="chart-point p3" /><div className="chart-point p4" /><div className="chart-months"><span>T5</span><span>T6</span><span>T7</span><span>T8</span><span>T9</span></div></div></div><div className="board-footer"><div><span className="legend-dot coffee" /> Cà phê <b>+42,8 tr</b></div><div><span className="legend-dot durian" /> Sầu riêng <b>+43,6 tr</b></div></div></div><div className="hero-float"><span>HÔM NAY</span><b>3 việc đã ghi</b><small>Vườn không còn là con số chung</small></div></div></div></section>
    <section className="proof-strip"><div className="container proof-inner"><p>Cho chủ vườn muốn biết rõ:</p><div><span>●</span> Tiền đang đi đâu</div><div><span>●</span> Cây nào đang sinh lời</div><div><span>●</span> Việc gì đã làm hôm nay</div></div></section>
    <section className="pain-section"><div className="container"><div className="section-intro"><p className="landing-eyebrow">01 / NỖI ĐAU THẬT</p><h2>Cuối vụ không nên<br /><em>là lúc bắt đầu đoán.</em></h2><p>Nông trại vận hành bằng rất nhiều quyết định nhỏ. Khi chúng nằm rải rác trong sổ, túi giấy và trí nhớ, bức tranh lớn luôn thiếu một mảnh.</p></div><div className="pain-grid">{painPoints.map(([number, title, copy]) => <article className="pain-item" key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="feature-section" id="demo"><div className="container"><div className="section-intro feature-intro"><p className="landing-eyebrow">02 / MỘT CÁCH LÀM GỌN HƠN</p><h2>Từ việc ngoài vườn<br /><em>đến quyết định đầu tư.</em></h2><p>Không biến chủ vườn thành nhân viên nhập liệu. Farm-Farmer gom đúng những gì cần biết, ở đúng thời điểm cần biết.</p></div><div className="feature-list">{featureData.map((feature) => <article className={`feature-row feature-${feature.kind}`} key={feature.kind}><div className="feature-copy"><span className="feature-number">{feature.number}</span><h3>{feature.title}</h3><p>{feature.copy}</p><Link to={feature.kind === 'journal' ? '/activity-logs' : '/register'}>Khám phá tính năng <span>↗</span></Link></div><div className="phone-wrap"><div className="phone"><div className="phone-speaker" /><PhoneScreen kind={feature.kind} /></div></div></article>)}</div></div></section>
    <section className="case-section"><div className="container case-grid"><div className="case-copy"><p className="landing-eyebrow">03 / MỘT VÍ DỤ CỤ THỂ</p><h2>Một vườn.<br /><em>Hai loại cây.<br />Một quyết định sáng hơn.</em></h2><p>Vườn Đồi Gió rộng 2 ha, trồng xen cà phê và sầu riêng. Thay vì nhìn một con số chi phí chung, chủ vườn có thể tách riêng từng loại cây để biết khoản đầu tư nào đang trả lời tốt nhất.</p><Link className="text-link" to="/register">Xem bản demo dữ liệu <span>↗</span></Link></div><div className="case-card"><div className="case-card-top"><span>VƯỜN ĐỒI GIÓ · 2 HA</span><span>VỤ 2026</span></div><div className="case-total"><small>TỔNG DOANH THU DỰ KIẾN</small><strong>246.800.000 đ</strong></div><div className="case-table"><div><span><i className="tree-coffee" /> Cà phê</span><b>+42.800.000 đ</b><small>Chi phí 38,2 tr · 1,4 ha</small></div><div><span><i className="tree-durian" /> Sầu riêng</span><b>+43.620.000 đ</b><small>Chi phí 62,1 tr · 0,6 ha</small></div></div><div className="case-foot">Lợi nhuận = Doanh thu − (Vật tư + Nhân công + Chi phí khác)</div></div></div></section>
    <section className="final-cta"><div className="container final-cta-inner"><div><p className="landing-eyebrow">BẮT ĐẦU TỪ VỤ NÀY</p><h2>Đừng để sổ tay<br />quyết định thay bạn.</h2></div><div><p>Ghi lại việc đầu tiên trong hôm nay. Miễn phí cho vườn đầu tiên, không cần thẻ thanh toán.</p><Link className="landing-primary light" to="/register">Dùng thử miễn phí <span>↗</span></Link></div></div></section>
    <footer className="landing-footer"><div className="container footer-grid"><div><div className="footer-brand">Farm<span>·</span>Farmer</div><p>Quản lý canh tác cây dài ngày bằng những dữ liệu bạn có thể tin.</p></div><div><b>HỖ TRỢ</b><a href="mailto:hello@farmfarmer.vn">hello@farmfarmer.vn</a><a href="tel:0900000000">090 000 0000</a></div><div><b>DỮ LIỆU</b><a href="#privacy">Chính sách dữ liệu</a><a href="#security">Bảo mật tài chính</a></div></div><div className="container footer-bottom"><span>© 2026 Farm-Farmer</span><span>Dữ liệu của bạn thuộc về bạn.</span></div></footer>
  </div>;
}

export default HomePage;
