import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

const data = {
 dashboard: { label:'TỔNG QUAN', title:'Buổi sáng ở nông trại', desc:'Theo dõi những gì đang diễn ra và việc cần làm tiếp theo.', path:'/journal' },
 journal: { label:'NHẬT KÝ CANH TÁC', title:'Ghi việc vừa làm', desc:'Một bản ghi tốt bắt đầu từ đúng lô, đúng việc, đúng chi phí.', path:'/journal' },
 inventory: { label:'VẬT TƯ & KHO', title:'Kho của bạn đang nói gì?', desc:'Theo dõi lượng dùng, tồn kho và những thứ sắp hết.', path:'/inventory' },
 finance: { label:'CHI PHÍ & ĐẦU TƯ', title:'Tiền đang đi đâu?', desc:'Tách rõ vật tư, nhân công và khoản đầu tư cho từng vụ.', path:'/finance' },
 revenue: { label:'DOANH THU & LỢI NHUẬN', title:'Lợi nhuận nhìn thấy được', desc:'Đặt doanh thu cạnh chi phí để có một con số đáng tin.', path:'/revenue' },
 ocr: { label:'OCR HÓA ĐƠN', title:'Đưa hóa đơn vào sổ', desc:'Chụp hoặc tải lên, kiểm tra lại, rồi liên kết vào chi phí.', path:'/ocr' },
 help: { label:'TRỢ GIÚP', title:'Có người đồng hành khi cần', desc:'Tìm câu trả lời nhanh hoặc gửi câu hỏi cho đội hỗ trợ.', path:'/help' },
};
const money = new Intl.NumberFormat('vi-VN');
function Kpis(){ return <div className="grid kpi-grid"><div className="panel kpi"><small>Chi phí vụ này</small><strong>{money.format(76220000)} đ</strong><span>↓ 6,2% so với vụ trước</span></div><div className="panel kpi"><small>Doanh thu dự kiến</small><strong>{money.format(204670000)} đ</strong><span>+12% theo sản lượng</span></div><div className="panel kpi"><small>Lợi nhuận tạm tính</small><strong>{money.format(128450000)} đ</strong><span>Biên lợi nhuận 62,7%</span></div><div className="panel kpi"><small>Nhật ký chờ đồng bộ</small><strong>03</strong><span className="badge warn">Đang offline</span></div></div> }
function Dashboard(){ return <><Kpis/><div className="data-grid"><section className="panel"><div className="section-title"><h2>Nhịp chi phí 6 tháng</h2><span className="badge">Cà phê / 2025</span></div><div className="bar-chart">{[42,55,48,68,58,82,66,90].map((h,i)=><i className="bar" style={{height:`${h}%`}} key={i}/>)}</div><div className="bar-labels">{['T5','T6','T7','T8','T9','T10','T11','T12'].map(x=><span key={x}>{x}</span>)}</div></section><section className="panel"><div className="section-title"><h2>Việc cần chú ý</h2><span className="badge danger">2 cảnh báo</span></div><p className="notice">Kho NPK 16-16-8 còn 18 kg, dưới ngưỡng an toàn.</p><p className="notice" style={{marginTop:10}}>Lô B2 đã 9 ngày chưa có nhật ký.</p><Link className="button secondary" style={{marginTop:16}} to="/inventory">Mở danh sách kho</Link></section></div><section className="panel" style={{marginTop:16}}><div className="section-title"><h2>Vườn đang canh tác</h2><Link to="/crops">Xem tất cả →</Link></div><div className="table-wrap"><table><thead><tr><th>Vườn / lô</th><th>Cây trồng</th><th>Nhật ký gần nhất</th><th>Trạng thái</th></tr></thead><tbody><tr><td>Vườn Đồi Gió / A1</td><td>Cà phê</td><td>Hôm nay, 07:42</td><td><span className="badge">Đang tốt</span></td></tr><tr><td>Vườn Đồi Gió / B2</td><td>Sầu riêng</td><td>9 ngày trước</td><td><span className="badge warn">Cần kiểm tra</span></td></tr><tr><td>Nhà kính số 2</td><td>Rau xà lách</td><td>Hôm qua</td><td><span className="badge">Đang tốt</span></td></tr></tbody></table></div></section></> }
function Journal(){ const [step,setStep]=useState(1); const [saved,setSaved]=useState(false); return <section className="panel journal-panel"><div className="steps"><span className={step>=1?'active':''}>1 Chọn lô</span><span className={step>=2?'active':''}>2 Ghi việc</span><span className={step>=3?'active':''}>3 Xác nhận</span></div>{saved?<div className="success-state"><span className="badge">Đã lưu offline</span><h2>Nhật ký đã nằm trong sổ.</h2><p>Bản ghi sẽ tự đồng bộ khi thiết bị có mạng. Bạn có thể tiếp tục công việc ngoài vườn.</p><button className="button" onClick={()=>{setSaved(false);setStep(1)}}>Ghi thêm nhật ký</button></div>:<><div className="form-grid"><label>Vườn / lô<select><option>Vườn Đồi Gió / A1</option><option>Vườn Đồi Gió / B2</option><option>Nhà kính số 2</option></select></label>{step>1&&<label>Loại công việc<select><option>Bón phân</option><option>Tưới nước</option><option>Phun thuốc sinh học</option><option>Thu hoạch</option></select></label>}</div>{step>1&&<div className="form-grid" style={{marginTop:14}}><label>Số lượng<input type="number" placeholder="Ví dụ: 25" /></label><label>Chi phí dự kiến<input type="number" placeholder="VNĐ" /></label></div>}{step>2&&<label style={{marginTop:14}}>Ghi chú<textarea placeholder="Điều gì đáng nhớ về công việc hôm nay?"/></label>}<div className="actions"><button className="button" onClick={()=>step<3?setStep(step+1):setSaved(true)}>{step<3?'Tiếp tục':'Lưu nhật ký'}</button>{step>1&&<button className="button secondary" onClick={()=>setStep(step-1)}>Quay lại</button>}</div></>}</section> }
function Inventory(){ const [q,setQ]=useState(''); const items=[['Phân hữu cơ vi sinh','Phân bón','420 kg','Đủ'],['NPK 16-16-8','Phân bón','18 kg','Sắp hết'],['Dầu neem','BVTV sinh học','12 chai','Đủ'],['Cây giống sầu riêng','Giống cây','86 cây','Đủ']]; const filtered=items.filter(x=>x.join(' ').toLowerCase().includes(q.toLowerCase())); return <section className="panel"><div className="section-title"><h2>Danh mục vật tư</h2><button className="button">+ Nhập vật tư</button></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm theo tên hoặc nhóm..."/><div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Tên vật tư</th><th>Nhóm</th><th>Tồn kho</th><th>Trạng thái</th></tr></thead><tbody>{filtered.map(x=><tr key={x[0]}><td>{x[0]}</td><td>{x[1]}</td><td>{x[2]}</td><td><span className={`badge ${x[3]==='Sắp hết'?'warn':''}`}>{x[3]}</span></td></tr>)}</tbody></table></div></section> }
function Finance({revenue=false}){ const [tab,setTab]=useState(revenue?'Doanh thu':'Nhân công'); const tabs=revenue?['Doanh thu','So sánh vụ']:['Nhân công','Đầu tư','Chi phí khác']; return <><div className="panel"><div className="tabs">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="form-grid" style={{marginTop:22}}><label>{revenue?'Lô bán hàng':'Hạng mục'}<input placeholder={revenue?'Ví dụ: Cà phê A1':'Ví dụ: Thu hái'}/></label><label>{revenue?'Sản lượng / doanh thu':'Số tiền'}<input type="number" placeholder="0"/></label></div><div className="actions"><button className="button">Lưu {tab.toLowerCase()}</button><button className="button secondary">Xuất báo cáo</button></div></div><div className="data-grid"><section className="panel"><div className="section-title"><h2>{revenue?'Doanh thu theo tháng':'Tổng hợp theo nhóm'}</h2></div><div className="bar-chart">{[35,45,58,48,74,66,88].map((h,i)=><i className="bar" style={{height:`${h}%`}} key={i}/>)}</div></section><section className="panel"><div className="section-title"><h2>Công thức</h2></div><p className="lede">Lợi nhuận = Doanh thu − Chi phí trực tiếp − Chi phí đầu tư phân bổ.</p><strong style={{fontSize:25}}>128.450.000 đ</strong></section></div></> }
function OCR(){ const [done,setDone]=useState(false); return <section className="panel ocr-panel"><div className="ocr-drop"><span className="eyebrow">BƯỚC 1 / TẢI HÓA ĐƠN</span><h2>{done?'Kiểm tra thông tin hóa đơn':'Đưa hóa đơn vào sổ'}</h2><p className="lede">{done?'Hệ thống đã đọc được các trường dưới đây. Bạn kiểm tra lại trước khi lưu.':'Chụp ảnh rõ toàn bộ hóa đơn, tránh bóng đổ và giữ máy song song mặt giấy.'}</p>{done?<><div className="form-grid"><label>Nhà cung cấp<input defaultValue="Cửa hàng Vật tư Tây Nguyên"/></label><label>Tổng tiền<input defaultValue="2.450.000"/></label><label>Ngày mua<input defaultValue="12/09/2025"/></label><label>Liên kết vườn<select><option>Vườn Đồi Gió / A1</option></select></label></div><div className="actions"><button className="button" onClick={()=>setDone(false)}>Xác nhận chi phí</button><button className="button secondary" onClick={()=>setDone(false)}>Chụp lại</button></div></>:<button className="button" onClick={()=>setDone(true)}>Chọn ảnh hóa đơn</button>}</div></section> }
function Help(){ const [q,setQ]=useState(''); const faqs=['Làm sao ghi nhật ký khi mất mạng?','Cách thêm một vườn mới','Tôi muốn mời người nhà cùng quản lý','Làm sao xuất báo cáo lợi nhuận?']; return <div className="data-grid"><section className="panel"><div className="section-title"><h2>Trung tâm trợ giúp</h2></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Bạn đang cần tìm gì?"/><div className="faq-list">{faqs.filter(x=>x.toLowerCase().includes(q.toLowerCase())).map(x=><button key={x}>{x}<span>→</span></button>)}</div></section><section className="panel"><p className="eyebrow">HỖ TRỢ TRỰC TIẾP</p><h2>Không tìm thấy câu trả lời?</h2><p className="lede">Gửi câu hỏi cho đội hỗ trợ Farm-Farmer. Chúng tôi thường phản hồi trong ngày làm việc.</p><button className="button terracotta">Gửi câu hỏi</button></section></div> }
export default function WorkspacePage({view}){ const meta=data[view]; const body=view==='dashboard'?<Dashboard/>:view==='journal'?<Journal/>:view==='inventory'?<Inventory/>:view==='finance'?<Finance/>:view==='revenue'?<Finance revenue/>:view==='ocr'?<OCR/>:<Help/>; return <main className="page-shell container"><div className="page-head"><div><p className="eyebrow">{meta.label}</p><h1>{meta.title}</h1><p className="lede">{meta.desc}</p></div>{view==='dashboard'&&<Link className="button" to="/journal">+ Ghi nhật ký hôm nay</Link>}</div>{body}</main> }
